### ISSUE TITLE
Input ERD

### ISSUE THREAD

**Issue by liavcueto375** [busi732/BUSI732_F24_Team3#9]

**Comment by letian0102** [comment]
**Objective**
As a data scientist, I will create an entity relationship diagram to demonstrate data flows in our system. This provides a clear understanding of how different data fields were connected. 
**Acceptance Criteria**
1. Generate an ERD that has all the datasets used and PK/FK connected correctly.
2. ERD should be easy to understand and crowfoot notations are required.
